/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'project' 
 * Target:  'HT32' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ht32f5xxxx_01.h"

/* Keil::Data Exchange:JSON:Jansson@2.7.0 */
#define JANSSON


#endif /* RTE_COMPONENTS_H */
