 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#include "GPIO.h"

//-----------------------------------------------------------------------------
void GPIO_Configuration(void)
{
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.PA    = 1;
  CKCUClock.Bit.PB    = 1;
  CKCUClock.Bit.PC    = 1;
  CKCUClock.Bit.PD    = 1;
  CKCUClock.Bit.AFIO  = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);


  GPIO_DirectionConfig    (IN_PA0_GPIO_PORT, IN_PA0_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA0_GPIO_PORT, IN_PA0_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA1_GPIO_PORT, IN_PA1_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA1_GPIO_PORT, IN_PA1_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA2_GPIO_PORT, IN_PA2_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA2_GPIO_PORT, IN_PA2_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA3_GPIO_PORT, IN_PA3_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA3_GPIO_PORT, IN_PA3_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA5_GPIO_PORT, IN_PA5_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA5_GPIO_PORT, IN_PA5_GPIO_PIN, ENABLE);

  GPIO_DirectionConfig    (IN_PA6_GPIO_PORT, IN_PA6_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA6_GPIO_PORT, IN_PA6_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA7_GPIO_PORT, IN_PA7_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA7_GPIO_PORT, IN_PA7_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC4_GPIO_PORT, IN_PC4_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC4_GPIO_PORT, IN_PC4_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC5_GPIO_PORT, IN_PC5_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC5_GPIO_PORT, IN_PC5_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC8_GPIO_PORT, IN_PC8_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC8_GPIO_PORT, IN_PC8_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC9_GPIO_PORT, IN_PC9_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC9_GPIO_PORT, IN_PC9_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC6_GPIO_PORT, IN_PC6_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC6_GPIO_PORT, IN_PC6_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC7_GPIO_PORT, IN_PC7_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC7_GPIO_PORT, IN_PC7_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB10_GPIO_PORT, IN_PB10_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB10_GPIO_PORT, IN_PB10_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB11_GPIO_PORT, IN_PB11_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB11_GPIO_PORT, IN_PB11_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB12_GPIO_PORT, IN_PB12_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB12_GPIO_PORT, IN_PB12_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PD0_GPIO_PORT, IN_PD0_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PD0_GPIO_PORT, IN_PD0_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB13_GPIO_PORT, IN_PB13_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB13_GPIO_PORT, IN_PB13_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB14_GPIO_PORT, IN_PB14_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB14_GPIO_PORT, IN_PB14_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB15_GPIO_PORT, IN_PB15_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB15_GPIO_PORT, IN_PB15_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC0_GPIO_PORT, IN_PC0_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC0_GPIO_PORT, IN_PC0_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC10_GPIO_PORT, IN_PC10_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC10_GPIO_PORT, IN_PC10_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC11_GPIO_PORT, IN_PC11_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC11_GPIO_PORT, IN_PC11_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC12_GPIO_PORT, IN_PC12_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC12_GPIO_PORT, IN_PC12_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC13_GPIO_PORT, IN_PC13_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC13_GPIO_PORT, IN_PC13_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA8_GPIO_PORT, IN_PA8_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA8_GPIO_PORT, IN_PA8_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA9_GPIO_PORT, IN_PA9_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA9_GPIO_PORT, IN_PA9_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA10_GPIO_PORT, IN_PA10_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA10_GPIO_PORT, IN_PA10_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA11_GPIO_PORT, IN_PA11_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA11_GPIO_PORT, IN_PA11_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA12_GPIO_PORT, IN_PA12_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA12_GPIO_PORT, IN_PA12_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA13_GPIO_PORT, IN_PA13_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA13_GPIO_PORT, IN_PA13_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA14_GPIO_PORT, IN_PA14_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA14_GPIO_PORT, IN_PA14_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PA15_GPIO_PORT, IN_PA15_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PA15_GPIO_PORT, IN_PA15_GPIO_PIN, DISABLE);

  GPIO_SetOutBits         (OUT_PB0_GPIO_PORT, OUT_PB0_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PB0_GPIO_PORT, OUT_PB0_GPIO_PIN, GPIO_DIR_OUT);
  GPIO_PullResistorConfig (OUT_PB0_GPIO_PORT, OUT_PB0_GPIO_PIN, GPIO_PR_UP);
  
  GPIO_DirectionConfig    (IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN, ENABLE);

  GPIO_DirectionConfig    (IN_PD1_GPIO_PORT, IN_PD1_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PD1_GPIO_PORT, IN_PD1_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PD2_GPIO_PORT, IN_PD2_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PD2_GPIO_PORT, IN_PD2_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PD3_GPIO_PORT, IN_PD3_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PD3_GPIO_PORT, IN_PD3_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN, ENABLE);

  GPIO_DirectionConfig    (IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN, ENABLE);

  GPIO_DirectionConfig    (IN_PB5_GPIO_PORT, IN_PB5_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB5_GPIO_PORT, IN_PB5_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB5_GPIO_PORT, IN_PB5_GPIO_PIN, GPIO_PR_UP);

  GPIO_DirectionConfig    (IN_PC15_GPIO_PORT, IN_PC15_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC15_GPIO_PORT, IN_PC15_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC1_GPIO_PORT, IN_PC1_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC1_GPIO_PORT, IN_PC1_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC2_GPIO_PORT, IN_PC2_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC2_GPIO_PORT, IN_PC2_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PC3_GPIO_PORT, IN_PC3_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PC3_GPIO_PORT, IN_PC3_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB6_GPIO_PORT, IN_PB6_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB6_GPIO_PORT, IN_PB6_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB7_GPIO_PORT, IN_PB7_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB7_GPIO_PORT, IN_PB7_GPIO_PIN, DISABLE);

  GPIO_DirectionConfig    (IN_PB8_GPIO_PORT, IN_PB8_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB8_GPIO_PORT, IN_PB8_GPIO_PIN, DISABLE);


  GPIO_ClearOutBits       (OUT_PA4_GPIO_PORT, OUT_PA4_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PA4_GPIO_PORT, OUT_PA4_GPIO_PIN, GPIO_DIR_OUT);

  GPIO_ClearOutBits       (OUT_PB4_GPIO_PORT, OUT_PB4_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PB4_GPIO_PORT, OUT_PB4_GPIO_PIN, GPIO_DIR_OUT);

  GPIO_ClearOutBits       (OUT_PC14_GPIO_PORT, OUT_PC14_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PC14_GPIO_PORT, OUT_PC14_GPIO_PIN, GPIO_DIR_OUT);
}

//-----------------------------------------------------------------------------


