 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------
#define IN_PA0_PORT           A
#define IN_PA0_PIN            0
#define IN_PA0_GPIO_CLK      STRCAT2(P,          IN_PA0_PORT)
#define IN_PA0_GPIO_ID       STRCAT2(GPIO_P,     IN_PA0_PORT)
#define IN_PA0_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA0_PORT)
#define IN_PA0_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA0_PIN)
#define IN_PA0_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA0_STATE         (GPIO_ReadInBit(IN_PA0_GPIO_PORT, IN_PA0_GPIO_PIN))

#define IN_PA1_PORT           A
#define IN_PA1_PIN            1
#define IN_PA1_GPIO_CLK      STRCAT2(P,          IN_PA1_PORT)
#define IN_PA1_GPIO_ID       STRCAT2(GPIO_P,     IN_PA1_PORT)
#define IN_PA1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA1_PORT)
#define IN_PA1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA1_PIN)
#define IN_PA1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA1_STATE         (GPIO_ReadInBit(IN_PA1_GPIO_PORT, IN_PA1_GPIO_PIN))

#define IN_PA2_PORT           A
#define IN_PA2_PIN            2
#define IN_PA2_GPIO_CLK      STRCAT2(P,          IN_PA2_PORT)
#define IN_PA2_GPIO_ID       STRCAT2(GPIO_P,     IN_PA2_PORT)
#define IN_PA2_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA2_PORT)
#define IN_PA2_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA2_PIN)
#define IN_PA2_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA2_STATE         (GPIO_ReadInBit(IN_PA2_GPIO_PORT, IN_PA2_GPIO_PIN))

#define IN_PA3_PORT           A
#define IN_PA3_PIN            3
#define IN_PA3_GPIO_CLK      STRCAT2(P,          IN_PA3_PORT)
#define IN_PA3_GPIO_ID       STRCAT2(GPIO_P,     IN_PA3_PORT)
#define IN_PA3_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA3_PORT)
#define IN_PA3_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA3_PIN)
#define IN_PA3_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA3_STATE         (GPIO_ReadInBit(IN_PA3_GPIO_PORT, IN_PA3_GPIO_PIN))

#define IN_PA5_PORT           A
#define IN_PA5_PIN            5
#define IN_PA5_GPIO_CLK      STRCAT2(P,          IN_PA5_PORT)
#define IN_PA5_GPIO_ID       STRCAT2(GPIO_P,     IN_PA5_PORT)
#define IN_PA5_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA5_PORT)
#define IN_PA5_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA5_PIN)
#define IN_PA5_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA5_STATE         (GPIO_ReadInBit(IN_PA5_GPIO_PORT, IN_PA5_GPIO_PIN))

#define IN_PA6_PORT           A
#define IN_PA6_PIN            6
#define IN_PA6_GPIO_CLK      STRCAT2(P,          IN_PA6_PORT)
#define IN_PA6_GPIO_ID       STRCAT2(GPIO_P,     IN_PA6_PORT)
#define IN_PA6_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA6_PORT)
#define IN_PA6_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA6_PIN)
#define IN_PA6_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA6_STATE         (GPIO_ReadInBit(IN_PA6_GPIO_PORT, IN_PA6_GPIO_PIN))

#define IN_PA7_PORT           A
#define IN_PA7_PIN            7
#define IN_PA7_GPIO_CLK      STRCAT2(P,          IN_PA7_PORT)
#define IN_PA7_GPIO_ID       STRCAT2(GPIO_P,     IN_PA7_PORT)
#define IN_PA7_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA7_PORT)
#define IN_PA7_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA7_PIN)
#define IN_PA7_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA7_STATE         (GPIO_ReadInBit(IN_PA7_GPIO_PORT, IN_PA7_GPIO_PIN))

#define IN_PC4_PORT           C
#define IN_PC4_PIN            4
#define IN_PC4_GPIO_CLK      STRCAT2(P,          IN_PC4_PORT)
#define IN_PC4_GPIO_ID       STRCAT2(GPIO_P,     IN_PC4_PORT)
#define IN_PC4_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC4_PORT)
#define IN_PC4_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC4_PIN)
#define IN_PC4_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC4_STATE         (GPIO_ReadInBit(IN_PC4_GPIO_PORT, IN_PC4_GPIO_PIN))

#define IN_PC5_PORT           C
#define IN_PC5_PIN            5
#define IN_PC5_GPIO_CLK      STRCAT2(P,          IN_PC5_PORT)
#define IN_PC5_GPIO_ID       STRCAT2(GPIO_P,     IN_PC5_PORT)
#define IN_PC5_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC5_PORT)
#define IN_PC5_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC5_PIN)
#define IN_PC5_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC5_STATE         (GPIO_ReadInBit(IN_PC5_GPIO_PORT, IN_PC5_GPIO_PIN))

#define IN_PC8_PORT           C
#define IN_PC8_PIN            8
#define IN_PC8_GPIO_CLK      STRCAT2(P,          IN_PC8_PORT)
#define IN_PC8_GPIO_ID       STRCAT2(GPIO_P,     IN_PC8_PORT)
#define IN_PC8_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC8_PORT)
#define IN_PC8_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC8_PIN)
#define IN_PC8_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC8_STATE         (GPIO_ReadInBit(IN_PC8_GPIO_PORT, IN_PC8_GPIO_PIN))

#define IN_PC9_PORT           C
#define IN_PC9_PIN            9
#define IN_PC9_GPIO_CLK      STRCAT2(P,          IN_PC9_PORT)
#define IN_PC9_GPIO_ID       STRCAT2(GPIO_P,     IN_PC9_PORT)
#define IN_PC9_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC9_PORT)
#define IN_PC9_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC9_PIN)
#define IN_PC9_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC9_STATE         (GPIO_ReadInBit(IN_PC9_GPIO_PORT, IN_PC9_GPIO_PIN))

#define IN_PC6_PORT           C
#define IN_PC6_PIN            6
#define IN_PC6_GPIO_CLK      STRCAT2(P,          IN_PC6_PORT)
#define IN_PC6_GPIO_ID       STRCAT2(GPIO_P,     IN_PC6_PORT)
#define IN_PC6_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC6_PORT)
#define IN_PC6_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC6_PIN)
#define IN_PC6_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC6_STATE         (GPIO_ReadInBit(IN_PC6_GPIO_PORT, IN_PC6_GPIO_PIN))

#define IN_PC7_PORT           C
#define IN_PC7_PIN            7
#define IN_PC7_GPIO_CLK      STRCAT2(P,          IN_PC7_PORT)
#define IN_PC7_GPIO_ID       STRCAT2(GPIO_P,     IN_PC7_PORT)
#define IN_PC7_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC7_PORT)
#define IN_PC7_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC7_PIN)
#define IN_PC7_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC7_STATE         (GPIO_ReadInBit(IN_PC7_GPIO_PORT, IN_PC7_GPIO_PIN))

#define IN_PB10_PORT           B
#define IN_PB10_PIN            10
#define IN_PB10_GPIO_CLK      STRCAT2(P,          IN_PB10_PORT)
#define IN_PB10_GPIO_ID       STRCAT2(GPIO_P,     IN_PB10_PORT)
#define IN_PB10_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB10_PORT)
#define IN_PB10_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB10_PIN)
#define IN_PB10_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB10_STATE         (GPIO_ReadInBit(IN_PB10_GPIO_PORT, IN_PB10_GPIO_PIN))

#define IN_PB11_PORT           B
#define IN_PB11_PIN            11
#define IN_PB11_GPIO_CLK      STRCAT2(P,          IN_PB11_PORT)
#define IN_PB11_GPIO_ID       STRCAT2(GPIO_P,     IN_PB11_PORT)
#define IN_PB11_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB11_PORT)
#define IN_PB11_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB11_PIN)
#define IN_PB11_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB11_STATE         (GPIO_ReadInBit(IN_PB11_GPIO_PORT, IN_PB11_GPIO_PIN))

#define IN_PB12_PORT           B
#define IN_PB12_PIN            12
#define IN_PB12_GPIO_CLK      STRCAT2(P,          IN_PB12_PORT)
#define IN_PB12_GPIO_ID       STRCAT2(GPIO_P,     IN_PB12_PORT)
#define IN_PB12_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB12_PORT)
#define IN_PB12_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB12_PIN)
#define IN_PB12_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB12_STATE         (GPIO_ReadInBit(IN_PB12_GPIO_PORT, IN_PB12_GPIO_PIN))

#define IN_PD0_PORT           D
#define IN_PD0_PIN            0
#define IN_PD0_GPIO_CLK      STRCAT2(P,          IN_PD0_PORT)
#define IN_PD0_GPIO_ID       STRCAT2(GPIO_P,     IN_PD0_PORT)
#define IN_PD0_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PD0_PORT)
#define IN_PD0_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PD0_PIN)
#define IN_PD0_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PD0_STATE         (GPIO_ReadInBit(IN_PD0_GPIO_PORT, IN_PD0_GPIO_PIN))

#define IN_PB13_PORT           B
#define IN_PB13_PIN            13
#define IN_PB13_GPIO_CLK      STRCAT2(P,          IN_PB13_PORT)
#define IN_PB13_GPIO_ID       STRCAT2(GPIO_P,     IN_PB13_PORT)
#define IN_PB13_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB13_PORT)
#define IN_PB13_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB13_PIN)
#define IN_PB13_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB13_STATE         (GPIO_ReadInBit(IN_PB13_GPIO_PORT, IN_PB13_GPIO_PIN))

#define IN_PB14_PORT           B
#define IN_PB14_PIN            14
#define IN_PB14_GPIO_CLK      STRCAT2(P,          IN_PB14_PORT)
#define IN_PB14_GPIO_ID       STRCAT2(GPIO_P,     IN_PB14_PORT)
#define IN_PB14_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB14_PORT)
#define IN_PB14_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB14_PIN)
#define IN_PB14_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB14_STATE         (GPIO_ReadInBit(IN_PB14_GPIO_PORT, IN_PB14_GPIO_PIN))

#define IN_PB15_PORT           B
#define IN_PB15_PIN            15
#define IN_PB15_GPIO_CLK      STRCAT2(P,          IN_PB15_PORT)
#define IN_PB15_GPIO_ID       STRCAT2(GPIO_P,     IN_PB15_PORT)
#define IN_PB15_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB15_PORT)
#define IN_PB15_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB15_PIN)
#define IN_PB15_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB15_STATE         (GPIO_ReadInBit(IN_PB15_GPIO_PORT, IN_PB15_GPIO_PIN))

#define IN_PC0_PORT           C
#define IN_PC0_PIN            0
#define IN_PC0_GPIO_CLK      STRCAT2(P,          IN_PC0_PORT)
#define IN_PC0_GPIO_ID       STRCAT2(GPIO_P,     IN_PC0_PORT)
#define IN_PC0_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC0_PORT)
#define IN_PC0_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC0_PIN)
#define IN_PC0_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC0_STATE         (GPIO_ReadInBit(IN_PC0_GPIO_PORT, IN_PC0_GPIO_PIN))

#define IN_PC10_PORT           C
#define IN_PC10_PIN            10
#define IN_PC10_GPIO_CLK      STRCAT2(P,          IN_PC10_PORT)
#define IN_PC10_GPIO_ID       STRCAT2(GPIO_P,     IN_PC10_PORT)
#define IN_PC10_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC10_PORT)
#define IN_PC10_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC10_PIN)
#define IN_PC10_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC10_STATE         (GPIO_ReadInBit(IN_PC10_GPIO_PORT, IN_PC10_GPIO_PIN))

#define IN_PC11_PORT           C
#define IN_PC11_PIN            11
#define IN_PC11_GPIO_CLK      STRCAT2(P,          IN_PC11_PORT)
#define IN_PC11_GPIO_ID       STRCAT2(GPIO_P,     IN_PC11_PORT)
#define IN_PC11_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC11_PORT)
#define IN_PC11_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC11_PIN)
#define IN_PC11_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC11_STATE         (GPIO_ReadInBit(IN_PC11_GPIO_PORT, IN_PC11_GPIO_PIN))

#define IN_PC12_PORT           C
#define IN_PC12_PIN            12
#define IN_PC12_GPIO_CLK      STRCAT2(P,          IN_PC12_PORT)
#define IN_PC12_GPIO_ID       STRCAT2(GPIO_P,     IN_PC12_PORT)
#define IN_PC12_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC12_PORT)
#define IN_PC12_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC12_PIN)
#define IN_PC12_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC12_STATE         (GPIO_ReadInBit(IN_PC12_GPIO_PORT, IN_PC12_GPIO_PIN))

#define IN_PC13_PORT           C
#define IN_PC13_PIN            13
#define IN_PC13_GPIO_CLK      STRCAT2(P,          IN_PC13_PORT)
#define IN_PC13_GPIO_ID       STRCAT2(GPIO_P,     IN_PC13_PORT)
#define IN_PC13_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC13_PORT)
#define IN_PC13_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC13_PIN)
#define IN_PC13_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC13_STATE         (GPIO_ReadInBit(IN_PC13_GPIO_PORT, IN_PC13_GPIO_PIN))

#define IN_PA8_PORT           A
#define IN_PA8_PIN            8
#define IN_PA8_GPIO_CLK      STRCAT2(P,          IN_PA8_PORT)
#define IN_PA8_GPIO_ID       STRCAT2(GPIO_P,     IN_PA8_PORT)
#define IN_PA8_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA8_PORT)
#define IN_PA8_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA8_PIN)
#define IN_PA8_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA8_STATE         (GPIO_ReadInBit(IN_PA8_GPIO_PORT, IN_PA8_GPIO_PIN))

#define IN_PA9_PORT           A
#define IN_PA9_PIN            9
#define IN_PA9_GPIO_CLK      STRCAT2(P,          IN_PA9_PORT)
#define IN_PA9_GPIO_ID       STRCAT2(GPIO_P,     IN_PA9_PORT)
#define IN_PA9_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA9_PORT)
#define IN_PA9_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA9_PIN)
#define IN_PA9_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA9_STATE         (GPIO_ReadInBit(IN_PA9_GPIO_PORT, IN_PA9_GPIO_PIN))

#define IN_PA10_PORT           A
#define IN_PA10_PIN            10
#define IN_PA10_GPIO_CLK      STRCAT2(P,          IN_PA10_PORT)
#define IN_PA10_GPIO_ID       STRCAT2(GPIO_P,     IN_PA10_PORT)
#define IN_PA10_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA10_PORT)
#define IN_PA10_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA10_PIN)
#define IN_PA10_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA10_STATE         (GPIO_ReadInBit(IN_PA10_GPIO_PORT, IN_PA10_GPIO_PIN))

#define IN_PA11_PORT           A
#define IN_PA11_PIN            11
#define IN_PA11_GPIO_CLK      STRCAT2(P,          IN_PA11_PORT)
#define IN_PA11_GPIO_ID       STRCAT2(GPIO_P,     IN_PA11_PORT)
#define IN_PA11_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA11_PORT)
#define IN_PA11_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA11_PIN)
#define IN_PA11_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA11_STATE         (GPIO_ReadInBit(IN_PA11_GPIO_PORT, IN_PA11_GPIO_PIN))

#define IN_PA12_PORT           A
#define IN_PA12_PIN            12
#define IN_PA12_GPIO_CLK      STRCAT2(P,          IN_PA12_PORT)
#define IN_PA12_GPIO_ID       STRCAT2(GPIO_P,     IN_PA12_PORT)
#define IN_PA12_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA12_PORT)
#define IN_PA12_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA12_PIN)
#define IN_PA12_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA12_STATE         (GPIO_ReadInBit(IN_PA12_GPIO_PORT, IN_PA12_GPIO_PIN))

#define IN_PA13_PORT           A
#define IN_PA13_PIN            13
#define IN_PA13_GPIO_CLK      STRCAT2(P,          IN_PA13_PORT)
#define IN_PA13_GPIO_ID       STRCAT2(GPIO_P,     IN_PA13_PORT)
#define IN_PA13_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA13_PORT)
#define IN_PA13_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA13_PIN)
#define IN_PA13_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA13_STATE         (GPIO_ReadInBit(IN_PA13_GPIO_PORT, IN_PA13_GPIO_PIN))

#define IN_PA14_PORT           A
#define IN_PA14_PIN            14
#define IN_PA14_GPIO_CLK      STRCAT2(P,          IN_PA14_PORT)
#define IN_PA14_GPIO_ID       STRCAT2(GPIO_P,     IN_PA14_PORT)
#define IN_PA14_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA14_PORT)
#define IN_PA14_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA14_PIN)
#define IN_PA14_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA14_STATE         (GPIO_ReadInBit(IN_PA14_GPIO_PORT, IN_PA14_GPIO_PIN))

#define IN_PA15_PORT           A
#define IN_PA15_PIN            15
#define IN_PA15_GPIO_CLK      STRCAT2(P,          IN_PA15_PORT)
#define IN_PA15_GPIO_ID       STRCAT2(GPIO_P,     IN_PA15_PORT)
#define IN_PA15_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PA15_PORT)
#define IN_PA15_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PA15_PIN)
#define IN_PA15_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PA15_STATE         (GPIO_ReadInBit(IN_PA15_GPIO_PORT, IN_PA15_GPIO_PIN))

#define OUT_PB0_PORT           B
#define OUT_PB0_PIN            0
#define OUT_PB0_GPIO_CLK      STRCAT2(P,          OUT_PB0_PORT)
#define OUT_PB0_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB0_PORT)
#define OUT_PB0_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB0_PORT)
#define OUT_PB0_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB0_PIN)
#define OUT_PB0_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB0_HIGH          OUT_PB0_GPIO_PORT->SRR    = OUT_PB0_GPIO_PIN
#define OUT_PB0_LOW           OUT_PB0_GPIO_PORT->RR     = OUT_PB0_GPIO_PIN
#define OUT_PB0_XOR           OUT_PB0_GPIO_PORT->DOUTR ^= OUT_PB0_GPIO_PIN

#define OUT_PB1_PORT           B
#define OUT_PB1_PIN            1
#define OUT_PB1_GPIO_CLK      STRCAT2(P,          OUT_PB1_PORT)
#define OUT_PB1_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB1_PORT)
#define OUT_PB1_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB1_PORT)
#define OUT_PB1_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB1_PIN)
#define OUT_PB1_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB1_HIGH          OUT_PB1_GPIO_PORT->SRR    = OUT_PB1_GPIO_PIN
#define OUT_PB1_LOW           OUT_PB1_GPIO_PORT->RR     = OUT_PB1_GPIO_PIN
#define OUT_PB1_XOR           OUT_PB1_GPIO_PORT->DOUTR ^= OUT_PB1_GPIO_PIN

#define IN_PB1_PORT           B
#define IN_PB1_PIN            1
#define IN_PB1_GPIO_CLK      STRCAT2(P,          IN_PB1_PORT)
#define IN_PB1_GPIO_ID       STRCAT2(GPIO_P,     IN_PB1_PORT)
#define IN_PB1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB1_PORT)
#define IN_PB1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB1_PIN)
#define IN_PB1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB1_STATE         (GPIO_ReadInBit(IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN))


#define IN_PD1_PORT           D
#define IN_PD1_PIN            1
#define IN_PD1_GPIO_CLK      STRCAT2(P,          IN_PD1_PORT)
#define IN_PD1_GPIO_ID       STRCAT2(GPIO_P,     IN_PD1_PORT)
#define IN_PD1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PD1_PORT)
#define IN_PD1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PD1_PIN)
#define IN_PD1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PD1_STATE         (GPIO_ReadInBit(IN_PD1_GPIO_PORT, IN_PD1_GPIO_PIN))

#define IN_PD2_PORT           D
#define IN_PD2_PIN            2
#define IN_PD2_GPIO_CLK      STRCAT2(P,          IN_PD2_PORT)
#define IN_PD2_GPIO_ID       STRCAT2(GPIO_P,     IN_PD2_PORT)
#define IN_PD2_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PD2_PORT)
#define IN_PD2_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PD2_PIN)
#define IN_PD2_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PD2_STATE         (GPIO_ReadInBit(IN_PD2_GPIO_PORT, IN_PD2_GPIO_PIN))

#define IN_PD3_PORT           D
#define IN_PD3_PIN            3
#define IN_PD3_GPIO_CLK      STRCAT2(P,          IN_PD3_PORT)
#define IN_PD3_GPIO_ID       STRCAT2(GPIO_P,     IN_PD3_PORT)
#define IN_PD3_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PD3_PORT)
#define IN_PD3_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PD3_PIN)
#define IN_PD3_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PD3_STATE         (GPIO_ReadInBit(IN_PD3_GPIO_PORT, IN_PD3_GPIO_PIN))

#define IN_PB2_PORT           B
#define IN_PB2_PIN            2
#define IN_PB2_GPIO_CLK      STRCAT2(P,          IN_PB2_PORT)
#define IN_PB2_GPIO_ID       STRCAT2(GPIO_P,     IN_PB2_PORT)
#define IN_PB2_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB2_PORT)
#define IN_PB2_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB2_PIN)
#define IN_PB2_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB2_STATE         (GPIO_ReadInBit(IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN))

#define IN_PB3_PORT           B
#define IN_PB3_PIN            3
#define IN_PB3_GPIO_CLK      STRCAT2(P,          IN_PB3_PORT)
#define IN_PB3_GPIO_ID       STRCAT2(GPIO_P,     IN_PB3_PORT)
#define IN_PB3_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB3_PORT)
#define IN_PB3_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB3_PIN)
#define IN_PB3_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB3_STATE         (GPIO_ReadInBit(IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN))

#define IN_PB5_PORT           B
#define IN_PB5_PIN            5
#define IN_PB5_GPIO_CLK      STRCAT2(P,          IN_PB5_PORT)
#define IN_PB5_GPIO_ID       STRCAT2(GPIO_P,     IN_PB5_PORT)
#define IN_PB5_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB5_PORT)
#define IN_PB5_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB5_PIN)
#define IN_PB5_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB5_STATE         (GPIO_ReadInBit(IN_PB5_GPIO_PORT, IN_PB5_GPIO_PIN))

#define IN_PC15_PORT           C
#define IN_PC15_PIN            15
#define IN_PC15_GPIO_CLK      STRCAT2(P,          IN_PC15_PORT)
#define IN_PC15_GPIO_ID       STRCAT2(GPIO_P,     IN_PC15_PORT)
#define IN_PC15_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC15_PORT)
#define IN_PC15_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC15_PIN)
#define IN_PC15_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC15_STATE         (GPIO_ReadInBit(IN_PC15_GPIO_PORT, IN_PC15_GPIO_PIN))

#define IN_PC1_PORT           C
#define IN_PC1_PIN            1
#define IN_PC1_GPIO_CLK      STRCAT2(P,          IN_PC1_PORT)
#define IN_PC1_GPIO_ID       STRCAT2(GPIO_P,     IN_PC1_PORT)
#define IN_PC1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC1_PORT)
#define IN_PC1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC1_PIN)
#define IN_PC1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC1_STATE         (GPIO_ReadInBit(IN_PC1_GPIO_PORT, IN_PC1_GPIO_PIN))

#define IN_PC2_PORT           C
#define IN_PC2_PIN            2
#define IN_PC2_GPIO_CLK      STRCAT2(P,          IN_PC2_PORT)
#define IN_PC2_GPIO_ID       STRCAT2(GPIO_P,     IN_PC2_PORT)
#define IN_PC2_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC2_PORT)
#define IN_PC2_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC2_PIN)
#define IN_PC2_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC2_STATE         (GPIO_ReadInBit(IN_PC2_GPIO_PORT, IN_PC2_GPIO_PIN))

#define IN_PC3_PORT           C
#define IN_PC3_PIN            3
#define IN_PC3_GPIO_CLK      STRCAT2(P,          IN_PC3_PORT)
#define IN_PC3_GPIO_ID       STRCAT2(GPIO_P,     IN_PC3_PORT)
#define IN_PC3_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PC3_PORT)
#define IN_PC3_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PC3_PIN)
#define IN_PC3_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PC3_STATE         (GPIO_ReadInBit(IN_PC3_GPIO_PORT, IN_PC3_GPIO_PIN))

#define IN_PB6_PORT           B
#define IN_PB6_PIN            6
#define IN_PB6_GPIO_CLK      STRCAT2(P,          IN_PB6_PORT)
#define IN_PB6_GPIO_ID       STRCAT2(GPIO_P,     IN_PB6_PORT)
#define IN_PB6_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB6_PORT)
#define IN_PB6_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB6_PIN)
#define IN_PB6_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB6_STATE         (GPIO_ReadInBit(IN_PB6_GPIO_PORT, IN_PB6_GPIO_PIN))

#define IN_PB7_PORT           B
#define IN_PB7_PIN            7
#define IN_PB7_GPIO_CLK      STRCAT2(P,          IN_PB7_PORT)
#define IN_PB7_GPIO_ID       STRCAT2(GPIO_P,     IN_PB7_PORT)
#define IN_PB7_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB7_PORT)
#define IN_PB7_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB7_PIN)
#define IN_PB7_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB7_STATE         (GPIO_ReadInBit(IN_PB7_GPIO_PORT, IN_PB7_GPIO_PIN))

#define IN_PB8_PORT           B
#define IN_PB8_PIN            8
#define IN_PB8_GPIO_CLK      STRCAT2(P,          IN_PB8_PORT)
#define IN_PB8_GPIO_ID       STRCAT2(GPIO_P,     IN_PB8_PORT)
#define IN_PB8_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB8_PORT)
#define IN_PB8_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB8_PIN)
#define IN_PB8_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB8_STATE         (GPIO_ReadInBit(IN_PB8_GPIO_PORT, IN_PB8_GPIO_PIN))



//-----------------------------------------------------------------------------
#define OUT_PA4_PORT           A
#define OUT_PA4_PIN            4
#define OUT_PA4_GPIO_CLK      STRCAT2(P,          OUT_PA4_PORT)
#define OUT_PA4_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA4_PORT)
#define OUT_PA4_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA4_PORT)
#define OUT_PA4_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA4_PIN)
#define OUT_PA4_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA4_HIGH          OUT_PA4_GPIO_PORT->SRR    = OUT_PA4_GPIO_PIN
#define OUT_PA4_LOW           OUT_PA4_GPIO_PORT->RR     = OUT_PA4_GPIO_PIN
#define OUT_PA4_XOR           OUT_PA4_GPIO_PORT->DOUTR ^= OUT_PA4_GPIO_PIN

#define OUT_PB4_PORT           B
#define OUT_PB4_PIN            4
#define OUT_PB4_GPIO_CLK      STRCAT2(P,          OUT_PB4_PORT)
#define OUT_PB4_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB4_PORT)
#define OUT_PB4_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB4_PORT)
#define OUT_PB4_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB4_PIN)
#define OUT_PB4_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB4_HIGH          OUT_PB4_GPIO_PORT->SRR    = OUT_PB4_GPIO_PIN
#define OUT_PB4_LOW           OUT_PB4_GPIO_PORT->RR     = OUT_PB4_GPIO_PIN
#define OUT_PB4_XOR           OUT_PB4_GPIO_PORT->DOUTR ^= OUT_PB4_GPIO_PIN

#define OUT_PC14_PORT           C
#define OUT_PC14_PIN            14
#define OUT_PC14_GPIO_CLK      STRCAT2(P,          OUT_PC14_PORT)
#define OUT_PC14_GPIO_ID       STRCAT2(GPIO_P,     OUT_PC14_PORT)
#define OUT_PC14_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PC14_PORT)
#define OUT_PC14_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PC14_PIN)
#define OUT_PC14_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PC14_HIGH          OUT_PC14_GPIO_PORT->SRR    = OUT_PC14_GPIO_PIN
#define OUT_PC14_LOW           OUT_PC14_GPIO_PORT->RR     = OUT_PC14_GPIO_PIN
#define OUT_PC14_XOR           OUT_PC14_GPIO_PORT->DOUTR ^= OUT_PC14_GPIO_PIN



//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif

